version: '3.1'

services:
    website:
        image: joomla:3.9
        restart: always
        links:
            - joomladb:database
        ports:
            - "80:80"
        environment:
            JOOMLA_DB_HOST: joomladb    # 'database' would work, too
            JOOMLA_DB_PASSWORD: changeme

    joomladb:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: changeme
